server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: devrajpk1992@gmail.com
    password: 123456

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  acount-sid: 3a809101d9fd9
  auth-token: b2880e41448666c
  from-number: 989797648
  

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans