razorpay:
  key: r_z_ptest_xxx
  secret: xxxxx

  webhook:
    secret: xxxxxx

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Pawan@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


